- .github/workflows/main.yml
- .gitmodules
- inouealc.c
- psqlodbc.h
- winbuild/BuildAll.ps1
- winbuild/psqlodbc.vcxproj
- winbuild/regress.ps1
We have a multi-threaded Windows application that was experiencing delays due to high lock contention in memory allocations from the PostgreSQL ODBC driver. We tried modifying the driver to use [mimalloc](https://github.com/microsoft/mimalloc), which is a memory allocator with better performance characteristics. After deploying this change, the delays due to lock contention disappeared. It has been running on thousands of our production deployments for 9 months without issue.
I've created this pull request so that others can benefit from this change by building the driver with the `_MIMALLOC_` symbol defined and linking to the mimalloc library. If building on Windows, `BuildAll.ps1` accepts a `-UseMimalloc` argument that does this for you (requires a toolset of `v141`, `v142` or later). …
> Use mimalloc to improve performance and reduce memory allocation lock contention

- .github/workflows/main.yml
This fixes the problem of the cache action incorrectly causing steps to be skipped when software versions are updated.
Note that changing the commands inside a step will not prevent that step from being skipped, but this should not be a problem once the workflow is stable. If this does occur, it can be resolved by adding a suffix to the cache key to force the creation of a new cache.
> Key caches based on software versions

- .github/workflows/main.yml
This PR creates a separate release for the mimalloc builds. This is needed because the mimalloc workflow artifacts have a limited retention period.
> Add mimalloc release

- psqlodbc.h
Prior to #6, psqlODBC only used `_strdup` on Windows builds. Although `_strdup` is part of ISO C and C++, it does not compile on all systems. 
Fixes #15.
> Use strdup on non-Windows systems

- bind.c
- connection.c
- convert.c
- descriptor.c
- descriptor.h
- dlg_specific.c
- parse.c
- results.c
- statement.c
- test/src/cte-test.c
- test/src/cursor-block-delete-test.c
- test/src/premature-test.c
Bunch of memory leaks, occuring in tests.
One heap-buffer-overrun in read operation at convert.c:3162.
Two memory leaks, detected by my unit tests:
password, conn_settings, pqopt fields overwrite if their values provided by both, system config and connstring.
Restored reference counting lifetime management of COL_INFO objects.
Some minor cosmetic changes.
> Fixed bugs, reported in issue #8.

- .github/workflows/main.yml
@davecramer we have a problem with the mimalloc release recursively triggering new releases. Please cancel the workflow and delete all the mimalloc releases except for the first one ([REL-16_00_0005-mimalloc](https://github.com/postgresql-interfaces/psqlodbc/releases/tag/REL-16_00_0005-mimalloc)).
This PR will prevent the problem from reoccurring.
> Prevent mimalloc release tag recursively triggering another release

- .gitignore
- connection.c
- parse.c
* Fix for issue #47 - double free of COL_INFO object due to refcount breakage during reuse of directly found object in getColumnsInfo(...).
* One more possible memory leak of COL_INFO objects in getColumnsInfo(...).
> Fix for issue #47 - double free of COL_INFO object

- connection.c
fix small memory leak of 'encoding' char array in 'CC_initial_log' function
> fix small memory leak in 'CC_initial_log' function

- winbuild/platformbuild.vcxproj
`BuildAll.ps1 -Target Rebuild` always reports an error that libpq.dll does not exist, caused by a typo in the error condition.
> Fix typo failing the Rebuild target

- pgxalib.cpp
These two calls have no effect because `std::string::empty()` only tests for emptiness, but does not cause it as apparently intended.
> Correct wrong string method calls

- environ.c
- psqlodbc.h
- statement.c
Old driver truncated the server error message incorrectly.
environ.c:147:
```c
error->errorsize = (Int2) errsize;
```
When `errsize` is larger than 32767, the errorsize is wrong.
environ.c:204:
```c
msglen = (SQLSMALLINT) strlen(msg);
```
`msglen` is truncated when msg is larger than 65535 bytes.
environ.c:224:
```c
RecNumber = 2 + (error->errorpos - 1) / error->recsize;
```
`errorpos` is used but never set.
In `PG_ErrorInfo`, makes `errsize`, `errpos` UInt4.
```c
typedef struct
{
UInt4	status;
UInt4	errsize;
UInt4	errpos;
UInt2	recsize;
char    sqlstate[6];
char    __error_message[44];
}       PG_ErrorInfo;
```
Fix `ER_Construct` and `ER_Dup` .
In `ER_ReturnError`, makes `msglen`, `wrtlen`, `pcblen` UInt4, and set `errpos` correctly.
```c
UInt4		stapos, msglen, wrtlen, pcblen;
```
```c …
```
> Fix PG_ErrorInfo and ER_ReturnError when error message is larger than 65535 bytes

- execute.c
- statement.c
- statement.h
> fix: spelling of stmt_deferred

- bind.c
- connection.c
- execute.c
- info.c
- odbcapi.c
- odbcapi30.c
- pgtypes.c
- results.c
- statement.c
- test/expected/catalogfunctions.out
- test/sampletables.sql
- test/src/catalogfunctions-test.c
Document functions, change catalogfunctions-test to use test_special table which has a primary key and unique index
> chore: Documentation and new test table for SQLSpecialColumns

- installer/psqlodbcm_cpu.wxs
The autogenerated component GUIDs were based on the same path and therefore were the same in both bitnesses. Installing both worked, but once one of them was uninstalled, the other's files remained despite its uninstallation finishing successfully.
I have no idea how this got through my testing; perhaps it only happens when both merge modules are installed via the same MSI.
> Fix duplicate component codes

- test/sampletables.sql
> test with just unique keys

- .github/workflows/main.yml
- psqlodbc.rc
This brings the dialogs up to a more modern look and feel that is consistent with current Windows versions. The table below contains the before and after screenshots for all impacted dialogs.
Visual Studio 2022 Community Edition was used to make these changes.
|Before|After|
|-|-|
|<img width="461" alt="Config Before" src="https://github.com/user-attachments/assets/3506725a-739f-49c6-9dfc-fa997993a469" />|<img width="539" alt="Config After" src="https://github.com/user-attachments/assets/5969eb4d-b4b5-433f-96be-0abe22233592" />|
|<img width="436" alt="Page 1 Before" src="https://github.com/user-attachments/assets/27285781-c01b-41b2-b1ea-03883dccebac" />|<img width="562" alt="Page 1 After" src="https://github.com/user-attachments/assets/c94e2f09-0268-4422-a0df-d01b0ae202cd" />|
|<img …
> Update the font and the layouts of all dialogs to improve their look and feel

- connection.c
- connection.h
- convert.c
- dlg_specific.c
- dlg_wingui.c
- info.c
- mylog.c
- odbcapi.c
- odbcapiw.c
- parse.c
- pgxalib.cpp
- psqlodbc.h
- qresult.h
- statement.c
The following functions
```
atoi()
atol()
atoll()
atof()
```
have been deprecated by the `strto...` variants. 
This commit adds a new set of macros prefixed with `pg_` in `psqlodbc.h` to convert the `ato..()` calls to their respective `strto...` versions.
> chore: replace unsafe string-to-number conversions

- bind.c
- connection.c
- connection.h
- convert.c
- descriptor.c
- dlg_specific.c
- drvconn.c
- environ.c
- info.c
- inouealc.c
- odbcapi30.c
- parse.c
- psqlodbc.h
- qresult.c
- results.c
- statement.c
- test/RegisterRegdsn.c
- test/src/bulkoperations-test.c
- test/src/common.h
- test/src/diagnostic-test.c
- test/src/numeric-test.c
- test/src/odbc-escapes-test.c
- test/src/result-conversions-test.c
`memset` can be declared as "unsafe" because compiler optimizations could remove it from the program.  This is especially problematic when we rely on it to clear out data containing sensitive information such as password.
This PR changes the calls against for `memset` to `pg_memset` and it does this differently depending on UNIX and Windows. 
UNIX: Change `memset` to use `memset_s`. `memset_s` is guaranteed to not be optimized away by the compiler. 
Windows: Windows cannot use `memset_s` because it is an optional function in C11 and MSVC does not provide an implementation for it. In order to mitigate this, we can use SecureZeroMemory instead.
> chore: change memset to memset_s/SecureZeroMemory

- dlg_specific.c
The current implementation of makeConnectString assumes that the input connect_string has size >= MAX_CONNECT_STRING, despite taking in a length argument.
The updated version ensures that the output string has min(len, MAX_CONNECT_STRING) chars written, properly terminated for either case.
> chore: update makeConnectString to not overflow connect_string where len < MAX_CONNECT_STRING

- Makefile.am
- convert.c
- dlg_specific.c
- execute.c
- info.c
- psqlodbc.h
- qresult.c
- results.c
- secure_sscanf.c
- secure_sscanf.h
- winbuild/psqlodbc.vcxproj
- winbuild/psqlsetup.vcxproj
Replaces the usages of sscanf() for a safer implementation
For character strings, the standard library uses the convention that strings are null-terminated: a string of n characters is represented as an array of n + 1 elements, the last of which is a NUL character ('\0'). For input conversion to various types, the C library provides the scanf() function family. The scanf() family of functions scans input according to supplied format string. This format may contain conversion specifications; the results from such conversions, if any, are stored in the locations pointed to by the pointer arguments that follow format. Each pointer argument must be of a type that is appropriate for the value returned by the corresponding conversion specification. scanf() also does not check the bounds of the …
> feat: safe sscanf

- psqlodbc.h
- test/src/bulkoperations-test.c
- test/src/common.h
- test/src/diagnostic-test.c
- test/src/numeric-test.c
- test/src/odbc-escapes-test.c
- test/src/result-conversions-test.c
A previous PR (https://github.com/postgresql-interfaces/psqlodbc/pull/105) replaced the instances of memset with memset_s or SecureZeroMemory because there's a chance that compiler may remove these calls during optimization. However, this PR will break builds with compilers that do not have memset_s. `memset_s` was introduced in C11, but it is flagged as optional and many compilers like GCC do not implement this.
For the time being, this commit will re-introduce memset if `memset_s` is not implemented in the compiler by checking `__STDC_LIB_EXT1__`  and defining `__STDC_WANT_LIB_EXT1__` before the needed imports. (reference: https://en.cppreference.com/w/c/string/byte/memset).
This commit also removes the changes in the unit test. `memset` should be safe in the unit tests. (previous …
> fix: use memset if memset_s is not available

- inouealc.c
A previous PR (#105) reverted some changes from (#104) which changes calls to memset_s back to memset due to memset_s not being supported by all compilers. This change reverts memset_s to memset in pgdebug_memset which was a missed change in #105
> fix: revert to memset for pgdebug_memset

- configure.ac
before using ac_cv_sizeof_bool
It was called after this conditional, so PG_USE_STDBOOL wasn't set even when it should be as shown in at the end of config.log:
ac_cv_header_stdbool_h=yes
ac_cv_sizeof_bool=1
ac_cv_type__Bool=yes
#define SIZEOF_BOOL 1
#define HAVE__BOOL 1
#define HAVE_STDBOOL_H 1
* fixes: https://github.com/postgresql-interfaces/psqlodbc/issues/110 https://github.com/postgresql-interfaces/psqlodbc/issues/94
> configure: make sure to call AC_CHECK_HEADER_STDBOOL

- odbcapi.c
SQLFreeStmt(stmt, SQL_DROP) now returns an error before trying to free statement resources
when its connection already has been closed.
A crash occurred when the PostgreSQL server terminated and a connection was subsequently attempted from an application when connection pooling by the driver manager was enabled and several pooled connections existed. In such cases, an invalid memory access would occur in ENTER_CONN_CS(conn) in SQLFreeStmt(), or an invalid address free() would be attempted in SC_clear_error() via PGAPI_FreeStmt().
"CC_cleanup()" doing "conn->status = CONN_NOT_CONNECTED" releases all statements belonging to the connection, so this change will probably not cause a resource leak.
> SQLFreeStmt(stmt,SQL_DROP) now returns an error when it's conn has been disconnected.

- dlg_wingui.c
Uses libqpq's Free for libqpq malloc'd String
Changes the generic `free()` function for the error message string allocated by `PQconninfoParse(..)` to use libpq's `PQfreemem(..)`
As per [PostgreSQL's libqpq documents](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PQCONNINFOPARSE), when using `PQconninfoParse(..)`:
> ... After processing the options array, free it by passing it to [PQconninfoFree](https://www.postgresql.org/docs/current/libpq-misc.html#LIBPQ-PQCONNINFOFREE). If this is not done, some memory is leaked for each call to [PQconninfoParse](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PQCONNINFOPARSE). **Conversely, if an error occurs and errmsg is not NULL, be sure to free the error string using …
> fix: use pgfree for libpq mallocs

- statement.c
Reverts postgresql-interfaces/psqlodbc#115
This breaks premature test
> Revert "fix double free stmt"

- connection.c
This made the build unreproducible. The Debian package has been patching out this information since 2016, with no ill effects reported.
> Remove __DATE__ from version message

- pgapi30.c
IRDGetField is treating its arguments as SQLINTEGER, but we were passing SQLSMALLINT to it.
Fixes the 2nd half of #51.
> Fix GetDescRec on big-endian architectures
